# The following line is needed
# when running the example site
# from a subdir of the theme
title = "Ouk Outdam"
enableRobotsTXT = true
theme = "not-much"
languageCode = "en-us"
baseURL = "https://oukoutdam.github.io/personal-hugo-site/"
copyright = "© {year} Ouk Outdam"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.highlight]
    style = 'dracula'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
theme = "auto"
palette = "eink"
showThemeNotice = true
showPostsSummary = true

# Giscus Comment System
# [params.giscus]
# repository = "username/repository"
# repositoryId = "repositoryId"
# categoryName = "categoryName"
# categoryId = "categoryId"
# mapping = "pathname"
# theme = "preferred_color_scheme"
# language = "en"
# lazyLoading = true

# Navigation
[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "Home"
    url = "/"
    weight = 1
    
  [[menu.main]]
    identifier = "resume"
    name = "résumé"
    title = "Résumé"
    url = "/resume"
    weight = 2

  [[menu.main]]
    identifier = "projects"
    name = "projects"
    title = "Projects"
    url = "/projects"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "contact"
    title = "Contact"
    url = "/contact"
    weight = 4


#  [[menu.main]]
#    identifier = "posts"
#    name = "posts"
#    title = "posts"
#    url = "/posts"
#    weight = 3
  
  
#   [[menu.main]]
#     identifier = "tags"
#     name = "tags"
#     title = "tags"
#     url = "/tags"
#     weight = 4

#   [[menu.main]]
#     identifier = "github"
#     name = "github"
#     title = "GitHub"
#     url = "https://github.com/imgios/not-much"
#     weight = 5
